// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularMonolith.Modules.FirstService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModularMonolith.Modules.FirstService.Data.Migrations
{
    [DbContext(typeof(FirstServiceDbContext))]
    partial class FirstServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("first_service")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModularMonolith.Modules.FirstService.Features.Books.Data.BookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.ToTable("books", "first_service");
                });

            modelBuilder.Entity("ModularMonolith.Shared.Data.SimpleOutbox.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("PublishAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_at");

                    b.Property<string>("PublisherName")
                        .HasColumnType("text")
                        .HasColumnName("publisher_name");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Content", "ModularMonolith.Shared.Data.SimpleOutbox.Entities.OutboxMessageEntity.Content#OutboxMessageEntityContent", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Headers")
                                .HasColumnType("jsonb")
                                .HasColumnName("content_headers");

                            b1.Property<string>("Payload")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("content_payload");

                            b1.Property<string>("Type")
                                .HasColumnType("text")
                                .HasColumnName("content_type");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TelemetryContext", "ModularMonolith.Shared.Data.SimpleOutbox.Entities.OutboxMessageEntity.TelemetryContext#OutboxMessageEntityTelemetryContext", b1 =>
                        {
                            b1.Property<string>("SpanId")
                                .IsRequired();

                            b1.Property<string>("TraceId")
                                .IsRequired();

                            b1
                                .ToJson("telemetry_context")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("State", "RetryCount", "PublishAt")
                        .HasDatabaseName("ix_outbox_messages_state_retry_count_publish_at");

                    b.ToTable("outbox_messages", "first_service");
                });
#pragma warning restore 612, 618
        }
    }
}
