# For more info on HTTP files go to https://aka.ms/vs/httpfile

@BaseUrl =http://localhost:5088

###ListStores
GET {{BaseUrl}}/second_service/api/stores
Accept: application/json

###GetStoreById
GET {{BaseUrl}}/second_service/api/stores/00000000-0000-0000-0000-000000000001
Accept: application/json

###CreateStore
POST {{BaseUrl}}/second_service/api/stores
Accept: application/json
Content-Type: application/json
Accept-Language: en-US

{
  "name": "Big Bad Store"
}

###UpdateStore
PUT {{BaseUrl}}/second_service/api/stores/00000000-0000-0000-0000-000000000001
Accept: application/json
Content-Type: application/json
Accept-Language: en-US

{
  "name": "Big Bad Store"
}

###DeleteStore
DELETE {{BaseUrl}}/second_service/api/stores/00000000-0000-0000-0000-000000000001
Accept: application/json